import React,{useEffect,useMemo,useState} from "react";
import {Activity,Bot,CheckCircle2,ChevronDown,Database,Filter,PauseCircle,Play,Radio,ServerCog,Telescope,XCircle} from "lucide-react";
import {api} from "../api";
import {useVoice} from "../voice/VoiceProvider";

const stageOrder=["baseline","anomaly","forecast","risk","explanation"];
const labels={baseline:"Adaptive baseline",anomaly:"Anomaly detector",forecast:"Trend forecast",risk:"Risk engine",explanation:"Explanation engine"};

export default function AITerminal(){
 const [status,setStatus]=useState(null),[diagnostics,setDiagnostics]=useState(null),[evidence,setEvidence]=useState([]),[error,setError]=useState(""),[testing,setTesting]=useState(false),[filter,setFilter]=useState("all"),[expanded,setExpanded]=useState(null),[lastUpdate,setLastUpdate]=useState(null);
 const {announce}=useVoice();
 async function refresh(){try{const [data,system,runs]=await Promise.all([api("/ai/status"),api("/system/diagnostics"),api("/ai/results?limit=20")]);setStatus(data);setDiagnostics(system);setEvidence(runs);setLastUpdate(new Date());setError("")}catch(e){setError(`Operations diagnostics unavailable: ${e.message}`)}}
 async function test(){setTesting(true);try{const r=await api("/ai/self-test",{method:"POST"});announce(`AI diagnostic complete. All five models passed. Risk engine returned ${r.result.risk.level} risk.`,{id:`test-${r.result.run_id}`});await refresh()}catch(e){setError(e.message);announce("AI diagnostic failed. Review the operations terminal.",{priority:"critical"})}finally{setTesting(false)}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,2500);return()=>clearInterval(timer)},[]);
 const logs=useMemo(()=>status?.logs?.filter(x=>filter==="all"||x.level===filter)||[],[status,filter]);
 const runs=useMemo(()=>{const ids=[];(status?.logs||[]).forEach(l=>{if(l.run_id&&!ids.includes(l.run_id))ids.push(l.run_id)});return ids.slice(0,8)},[status]);
 return <div className="ai-workspace">
  <section className="ops-hero"><div className="ops-identity"><div className="pulse-orb"><Bot/></div><div><span className="eyebrow">LIVE MODEL OBSERVABILITY</span><h2>AI Operations Command Center</h2><p>Real execution evidence from sensor intake through model decision and precaution policy.</p></div></div><div className="ops-actions"><div className={`live-pill ${error?"down":""}`}><Radio size={14}/>{error?"CONNECTION LOST":"LIVE · 2.5 SEC"}</div><button className="primary" onClick={test} disabled={testing}><Play size={16}/>{testing?"Executing diagnostics…":"Run full diagnostic"}</button></div></section>
  {error&&<div className="terminal-error"><XCircle/>{error}<button onClick={refresh}>Retry</button></div>}
  <section className="runtime-strip"><Metric label="Runtime" value={status?.status||"connecting"}/><Metric label="Version" value={status?.version||"—"}/><Metric label="Operational nodes" value={`${status?.models?.filter(m=>["healthy","ready"].includes(m.status)).length||0}/${status?.models?.length||5}`}/><Metric label="Tracked runs" value={runs.length}/><Metric label="Last synchronized" value={lastUpdate?.toLocaleTimeString()||"—"}/></section>
  <section className="diagnostic-panel"><div className="section-heading"><div><ServerCog/><div><h3>Platform dependency diagnostics</h3><p>Live connectivity checks with latency and error evidence</p></div></div><span className={diagnostics?.status||"checking"}>{diagnostics?.status||"checking"}</span></div><div className="component-health">{diagnostics?.components?.map(component=><div className={component.status} key={component.name}>{component.status==="healthy"?<CheckCircle2/>:<XCircle/>}<span><b>{component.name}</b><small>{component.latency_ms} ms · {typeof component.detail==="string"?component.detail:JSON.stringify(component.detail)}</small></span></div>)||<div className="empty-state">Running dependency checks...</div>}</div><div className="evidence-strip"><div><Database/><span><small>Persisted AI analyses</small><b>{diagnostics?.evidence?.ai_analyses||0}</b></span></div><div><Activity/><span><small>AI-linked alerts</small><b>{diagnostics?.evidence?.ai_linked_alerts||0}</b></span></div><div className={diagnostics?.evidence?.telemetry_events_without_ai?"error":""}><XCircle/><span><small>Telemetry missing AI</small><b>{diagnostics?.evidence?.telemetry_events_without_ai||0}</b></span></div></div></section>
  <section className="pipeline-map"><div className="pipeline-caption"><div><Activity size={18}/><b>Linear inference pipeline</b></div><span>Downstream stages are held when an upstream dependency fails</span></div><div className="pipeline-nodes">{stageOrder.map((name,index)=>{const model=status?.models?.find(m=>m.name===name),blocked=model?.status==="blocked";return <React.Fragment key={name}><div className={`pipeline-node ${model?.status||"waiting"}`}><div className="node-status">{model?.status==="error"?<XCircle/>:blocked?<PauseCircle/>:<CheckCircle2/>}</div><span>0{index+1} · {blocked?"HELD":model?.status||"waiting"}</span><b>{labels[name]}</b><small>{blocked?`Blocked by ${labels[model.blocked_by]||model.blocked_by}`:`${model?.runs||0} runs · ${model?.latency_ms??"—"} ms`}</small></div>{index<stageOrder.length-1&&<div className={`pipeline-link ${model?.status==="error"||blocked?"stopped":""}`}><i/></div>}</React.Fragment>})}</div></section>
  <div className="terminal-columns"><section className="run-ledger"><div className="section-heading"><div><Telescope/><div><h3>Persisted analysis evidence</h3><p>Database-linked AI runs and originating events</p></div></div></div>{evidence.length?evidence.map(run=><button key={run.id} className="run-row"><div className="run-icon"><Activity/></div><div><b>AI {run.id.slice(0,8)}</b><span>Event {run.core_event_id.slice(0,8)} · {new Date(run.analysis_timestamp).toLocaleTimeString()}</span></div><em className={run.risk?.level||run.status}>{run.risk?.level||run.status}</em><ChevronDown/></button>):<div className="empty-state">No persisted AI analysis yet. Publish a scenario from the external Test Lab.</div>}</section>
   <section className="event-console"><div className="console-toolbar"><div><span className="status-dot"/><b>Structured event stream</b></div><div className="log-filters"><Filter size={14}/>{["all","info","warning","error"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="console-scroll">{logs.length?logs.map(log=><div className={`event-line ${log.level} ${expanded&&log.run_id!==expanded?"muted":""}`} key={log.id||log.timestamp+log.message}><time>{new Date(log.timestamp).toLocaleTimeString()}</time><span className="event-level">{log.level}</span><div><b>{log.component} · {log.event||"runtime"}</b><p>{log.message}</p>{Object.keys(log.details||{}).length>0&&<details><summary>Inspect model data</summary><pre>{JSON.stringify(log.details,null,2)}</pre></details>}</div></div>):<div className="empty-state">Waiting for AI runtime events…</div>}</div></section>
  </div>
 </div>
}
function Metric({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
