import React,{useEffect,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {Activity,AlertTriangle,BellRing,BrainCircuit,CheckCircle2,ClipboardCheck,Cpu,ExternalLink,FileBarChart,LayoutDashboard,LockKeyhole,LogOut,Menu,RefreshCw,Server,Settings,ShieldCheck,SlidersHorizontal,Volume2,VolumeX,X} from "lucide-react";
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {api,login} from "./api";
import AITerminal from "./components/AITerminal";
import {VoiceProvider,useVoice} from "./voice/VoiceProvider";
import "./styles.css";

const navigation=[
 {section:"OPERATIONS",items:[{name:"Overview",icon:LayoutDashboard},{name:"Devices",icon:Server},{name:"Telemetry",icon:Activity},{name:"Alerts",icon:AlertTriangle},{name:"Incidents",icon:ClipboardCheck},{name:"AI Operations",icon:BrainCircuit}]},
 {section:"MANAGE",items:[{name:"Reports",icon:FileBarChart},{name:"Settings",icon:SlidersHorizontal},{name:"Administration",icon:Settings}]},
];

const defaultPreferences={voiceRepeatSeconds:10,showTickets:true,showTrend:true,showAlertFeed:true,reportSeverity:true,reportHealth:true,reportFindings:true};
function savedPreferences(){try{return {...defaultPreferences,...JSON.parse(localStorage.getItem("vtab.preferences")||"{}")} }catch{return defaultPreferences}}

function Login(){const [error,setError]=useState("");async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await login(f.get("email"),f.get("password"));location.reload()}catch(x){setError(x.message)}}return <main className="login"><form onSubmit={submit}><div className="logo"><ShieldCheck/> VTAB Sentinel</div><h1>Server room intelligence</h1><p>Secure operator access</p><label>Email<input name="email" defaultValue="admin@vtab.local"/></label><label>Password<input name="password" type="password" defaultValue="Admin123!"/></label>{error&&<div className="error">{error}</div>}<button>Sign in</button></form></main>}

function App(){
 const [page,setPage]=useState("Overview"),[summary,setSummary]=useState({}),[telemetry,setTelemetry]=useState([]),[alerts,setAlerts]=useState([]),[incidents,setIncidents]=useState([]),[devices,setDevices]=useState([]),[sensors,setSensors]=useState([]),[loading,setLoading]=useState(false),[menu,setMenu]=useState(false),[lastSync,setLastSync]=useState(null),[preferences,setPreferences]=useState(savedPreferences);
 const {enabled,speaking,lastMessage,toggle,announce,supported}=useVoice();const spoken=useRef(new Set(JSON.parse(sessionStorage.getItem("spokenAlerts")||"[]"))),incidentRef=useRef(incidents),summaryRef=useRef(summary),previousState=useRef(null);incidentRef.current=incidents;summaryRef.current=summary;
 async function load(){setLoading(true);try{const [s,t,a,i,d,se]=await Promise.all([api("/reports/summary"),api("/telemetry/latest?limit=250"),api("/alerts"),api("/incidents"),api("/devices"),api("/master/sensors")]);setSummary(s);setTelemetry(t);setAlerts(a);setIncidents(i);setDevices(d);setSensors(se);setLastSync(new Date());const cutoff=Date.now()-45000;const fresh=a.filter(x=>new Date(x.event_timestamp||x.created_at).getTime()>=cutoff&&!spoken.current.has(x.id));const groups=Object.values(fresh.reduce((acc,x)=>{const key=x.core_event_id||x.id;(acc[key]??=[]).push(x);return acc},{}));groups.forEach(group=>{group.forEach(x=>spoken.current.add(x.id));const critical=group.some(x=>x.severity==="critical");const messages=[...new Set(group.map(x=>x.message||x.alert_type.replaceAll("_"," ")))];const actions=[...new Set(group.map(x=>x.recommendation).filter(Boolean))].slice(0,2);announce(`${critical?"Critical server-room incident":"Server-room attention required"}. ${messages.join(" ")} ${actions.length?`Recommended action: ${actions.join(" ")}`:""}`,{priority:critical?"critical":"normal",id:`event-${group[0].core_event_id||group[0].id}`})});sessionStorage.setItem("spokenAlerts",JSON.stringify([...spoken.current].slice(-200)))}catch(e){console.error(e)}finally{setLoading(false)}}
 useEffect(()=>{load();const timer=setInterval(load,3000);const navigate=e=>setPage(e.detail);window.addEventListener("vtab:navigate",navigate);return()=>{clearInterval(timer);window.removeEventListener("vtab:navigate",navigate)}},[announce]);
 useEffect(()=>{const current={alerts:summary.open_alerts||0,tickets:summary.open_incidents||0},previous=previousState.current;if(previous&&current.alerts===0&&previous.alerts>0){announce(current.tickets?`The monitored condition has normalized, but ${current.tickets} operator ticket${current.tickets===1?" remains":"s remain"} open. The responsible technician should verify the recovery and close the ticket.`:"The monitored condition has normalized and all related tickets are closed. The server room has returned to healthy operation.",{id:`recovery-${Date.now()}`})}else if(previous&&current.alerts===0&&current.tickets===0&&previous.tickets>0){announce("The monitored condition is normalized and the final operator ticket has been closed. The server room is healthy.",{id:`workflow-clear-${Date.now()}`})}previousState.current=current},[summary.open_alerts,summary.open_incidents,announce]);
 useEffect(()=>{const seconds=Number(preferences.voiceRepeatSeconds);if(!enabled||!seconds)return;const remind=()=>{const active=incidentRef.current.filter(x=>["open","assigned","acknowledged"].includes(x.status));if(!active.length)return;const environmentNormalized=(summaryRef.current.open_alerts||0)===0;if(environmentNormalized){announce(`The monitored condition is normalized, but ${active.length} operator ticket${active.length===1?" remains":"s remain"} open. Please verify the recovery and close the pending ticket.`,{id:`normalized-reminder-${Date.now()}`});return}const critical=active.some(x=>x.severity==="critical"),messages=[...new Set(active.slice(0,3).map(x=>x.message))];announce(`${critical?"Critical reminder":"Attention reminder"}. ${messages.join(" ")} ${active.length} active ticket${active.length===1?"":"s"} require operator action.`,{priority:critical?"critical":"normal",id:`ticket-reminder-${Date.now()}`})};const timer=setInterval(remind,seconds*1000);return()=>clearInterval(timer)},[enabled,preferences.voiceRepeatSeconds,announce]);
 function updatePreference(key,value){setPreferences(current=>{const next={...current,[key]:value};localStorage.setItem("vtab.preferences",JSON.stringify(next));return next})}
 const chart=telemetry.filter(x=>x.measurement_type==="temperature").slice().reverse().map(x=>({time:new Date(x.measurement_timestamp).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}),value:x.value_numeric}));
 function navigate(name){setPage(name);setMenu(false)}
 async function closeTicket(id){if(!confirm("Close this ticket as successfully handled?"))return;await api(`/incidents/${id}`,{method:"PATCH",body:JSON.stringify({action:"close",note:"Closed by operator after successful verification"})});await load()}
 async function resetData(){if(!confirm("Delete all telemetry, alerts, tickets and AI test history? Devices and users will be preserved."))return;await api("/admin/test-data/reset",{method:"POST"});sessionStorage.removeItem("spokenAlerts");spoken.current.clear();await load();alert("Test data cleared. The next records will come from the simulator or hardware.")}
 const state=summary.system_state||((summary.open_alerts||0)>0?"alert":(summary.open_incidents||0)>0?"pending":"healthy");
 return <div className={`shell system-${state}`}><aside className={menu?"open":""}><button className="mobile-close" onClick={()=>setMenu(false)}><X/></button><div className="brand"><div><ShieldCheck/></div><b>VTAB <span>SENTINEL</span></b><small>AI OPERATIONS PLATFORM</small></div>{navigation.map(group=><nav key={group.section}><label>{group.section}</label>{group.items.map(({name,icon:Icon})=><button className={page===name?"active":""} onClick={()=>navigate(name)} key={name}><Icon size={17}/><span>{name}</span></button>)}</nav>)}<div className="sidebar-status"><span><i/>{state==="healthy"?"Platform healthy":"Operator attention required"}</span><small>Live database state</small></div><button className="logout" onClick={()=>{localStorage.clear();location.reload()}}><LogOut size={16}/> Sign out</button></aside><main><header><button className="mobile-menu" onClick={()=>setMenu(true)}><Menu/></button><div><small>AI SERVER ROOM MONITORING</small><h1>{page}</h1></div><div className="header-actions"><button title="Global setting: applies to every VTAB page" className={`voice-toggle ${enabled?"enabled":""} ${speaking?"speaking":""}`} onClick={toggle}>{enabled?<Volume2 size={17}/>:<VolumeX size={17}/>}<span><b>Voice intelligence</b><small>{!supported?"Not supported":speaking?"Speaking now":enabled?"Enabled system-wide":"Muted system-wide"}</small></span></button><button className="refresh" onClick={load}><RefreshCw size={16} className={loading?"spin":""}/> Refresh</button></div></header><section className={`system-banner ${state}`}>{state==="healthy"?<CheckCircle2/>:<AlertTriangle/>}<div><b>{state==="healthy"?"All monitored conditions are healthy":"Active server-room attention required"}</b><span>{state==="healthy"?"No open alerts or tickets. Monitoring continues in real time.":`${summary.open_incidents||0} open ticket(s) and ${summary.open_alerts||0} active alert(s).`}</span></div></section>
 {speaking&&<div className="voice-now"><div className="voice-wave"><i/><i/><i/><i/></div><div><b>VTAB voice intelligence</b><span>{lastMessage}</span></div><button onClick={toggle}><VolumeX/> Mute globally</button></div>}
 {page==="Overview"&&<><section className="cards"><Card icon={<Server/>} label="Devices" value={summary.devices||0}/><Card icon={<Activity/>} label="Telemetry points" value={summary.telemetry_points||0}/><Card icon={<AlertTriangle/>} label="Open alerts" value={summary.open_alerts||0} warn/><Card icon={<ClipboardCheck/>} label="Open tickets" value={summary.open_incidents||0}/></section>{preferences.showTickets&&<TicketQueue title="Tickets requiring action" rows={incidents.filter(x=>["open","assigned","acknowledged"].includes(x.status)).slice(0,5)} onClose={closeTicket} onViewAll={()=>setPage("Incidents")}/>} {preferences.showTrend&&<LiveTrend chart={chart} lastSync={lastSync}/>} {preferences.showAlertFeed&&<AlertFeed title="Live alert feed" rows={alerts.slice(0,6)} onOpen={()=>setPage("Alerts")}/>}</>}
 {page==="Devices"&&<DeviceInventory devices={devices} sensors={sensors} telemetry={telemetry}/>} 
 {page==="Telemetry"&&<TelemetryDashboard telemetry={telemetry}/>} 
 {page==="Alerts"&&<AlertFeed title="Alerts and recommended actions" rows={alerts}/>} 
 {page==="Incidents"&&<IncidentCenter incidents={incidents} onClose={closeTicket}/>} 
 {page==="AI Operations"&&<AITerminal/>}
 {page==="Reports"&&<OperationalReports summary={summary} alerts={alerts} incidents={incidents} preferences={preferences}/>} 
 {page==="Settings"&&<ApplicationSettings preferences={preferences} updatePreference={updatePreference}/>} 
 {page==="Administration"&&<section className="admin-grid"><div className="panel"><Settings/><h2>Clean test workspace</h2><p>Remove telemetry, alerts, tickets and AI results while preserving users, devices and configuration.</p><button className="danger-button" onClick={resetData}><RefreshCw/> Clear all test data</button></div><div className="panel"><LockKeyhole/><h2>System-wide voice policy</h2><p>Voice intelligence is currently <b>{enabled?"enabled":"muted"}</b>. The global header control applies across every page and persists after refresh.</p><button className="primary" onClick={toggle}>{enabled?<VolumeX/>:<Volume2/>}{enabled?"Mute voice system-wide":"Enable voice system-wide"}</button></div><div className="panel test-callout"><ExternalLink/><h2>Unified simulator</h2><p>Hardware/ESP32 and software/AI tests now share one simulator application. Both paths publish through MQTT.</p><a className="primary" href="http://localhost:5174" target="_blank" rel="noreferrer"><ExternalLink/> Open unified simulator</a></div></section>}
 </main></div>
}

function LiveTrend({chart,lastSync}){const danger=(chart.at(-1)?.value||0)>30,color=danger?"#ff5d74":"#2ee6c5";return <section className={`panel live-trend ${danger?"danger":"healthy"}`}><div className="section-heading"><div><Activity/><div><h3>Live temperature trend</h3><p>Every validated ESP32 reading appears here automatically</p></div></div><span className={`live-pill ${danger?"down":""}`}><i/> {danger?"HAZARD":"LIVE"} · {lastSync?lastSync.toLocaleTimeString():"connecting"}</span></div>{chart.length?<div className="chart"><ResponsiveContainer><AreaChart data={chart}><defs><linearGradient id="temperatureFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.4}/><stop offset="100%" stopColor={color} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#143247" strokeDasharray="4 5"/><XAxis dataKey="time" minTickGap={30} stroke="#638298" fontSize={10}/><YAxis domain={[10,55]} stroke="#638298" fontSize={10} unit="°"/><Tooltip contentStyle={{background:"#081422",border:`1px solid ${color}`}}/><ReferenceLine y={30} stroke="#ffbd5a" strokeDasharray="5 4" label={{value:"Alert 30°C",fill:"#ffbd5a",fontSize:10}}/><Area type="monotone" dataKey="value" name="Temperature °C" stroke={color} fill="url(#temperatureFill)" strokeWidth={3} dot={chart.length<4?{r:6,fill:color}:false} activeDot={{r:7,fill:color}} isAnimationActive/></AreaChart></ResponsiveContainer></div>:<div className="chart-empty"><span className="pulse-ring"><Activity/></span><b>Waiting for the first ESP32 transmission</b><p>The independent Test Lab starts streaming automatically.</p></div>}</section>}

const hardwareMap={temperature:"DHT22 / AM2302",humidity:"DHT22 / AM2302",water_leak:"HW-038 water probe",door_open:"MC-38 magnetic contact",smoke:"MQ-2 smoke sensor"};
function latestByType(rows){return rows.reduce((out,row)=>{if(!out[row.measurement_type])out[row.measurement_type]=row;return out},{})}
function DeviceInventory({devices,sensors,telemetry}){const latest=latestByType(telemetry);const types=["temperature","humidity","water_leak","door_open","smoke"];return <><section className="panel equipment-head"><div><Cpu/><div><h2>ESP32 edge controller</h2><p>The Wi-Fi board and every sensor module connected to it</p></div></div><span className="live-pill"><i/> {devices[0]?.status||"registered"}</span></section><section className="equipment-grid">{devices.map(d=><article className="equipment-card controller" key={d.id}><Cpu/><small>EDGE CONTROLLER</small><h3>{d.name}</h3><b>{d.hardware_type||"ESP32-WROOM-32"}</b><p>Firmware {d.firmware_version||"not reported"}</p><footer>Last packet: {relativeTime(d.last_seen_at)}</footer></article>)}{types.map(type=>{const row=latest[type];const registered=sensors.find(s=>(s.sensor_type||s.measurement_type||s.name||"").toLowerCase().includes(type.replace("_"," "))||s.sensor_type===type);const triggered=row&&(type==="temperature"?row.value_numeric>30:type==="humidity"?row.value_numeric>70:row.value_numeric===1);return <article className={`equipment-card ${triggered?"sensor-alert":""}`} key={type}><Activity/><small>SENSOR MODULE</small><h3>{type.replaceAll("_"," ")}</h3><b>{hardwareMap[type]}</b><p>{row?`${row.value_numeric} ${row.unit||""}`:"Waiting for telemetry"}</p><footer>{registered?"Registered":"Mapped from ESP32 packet"} · {row?relativeTime(row.measurement_timestamp):"No reading"}</footer></article>})}</section></>}

function TelemetryDashboard({telemetry}){
 const latest=latestByType(telemetry),series={};
 telemetry.slice().reverse().forEach(r=>{const key=r.measurement_timestamp;(series[key]??={time:new Date(key).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})})[r.measurement_type]=r.value_numeric});
 const chart=Object.values(series).slice(-60);
 return <><section className="sensor-kpis">{["temperature","humidity","water_leak","door_open","smoke"].map(type=><article className={latest[type]?.value_numeric===1||type==="temperature"&&latest[type]?.value_numeric>30||type==="humidity"&&latest[type]?.value_numeric>70?"active":""} key={type}><small>{type.replaceAll("_"," ")}</small><strong>{latest[type]?`${latest[type].value_numeric} ${latest[type].unit||""}`:"—"}</strong><span>{latest[type]?relativeTime(latest[type].measurement_timestamp):"Awaiting data"}</span></article>)}</section>
 <section className="panel"><div className="section-heading"><div><Activity/><div><h3>Live environmental telemetry</h3><p>Temperature and humidity over time with operational thresholds</p></div></div></div>{chart.length?<div className="chart large"><ResponsiveContainer><LineChart data={chart}><CartesianGrid stroke="#143247" strokeDasharray="4 5"/><XAxis dataKey="time" minTickGap={35} stroke="#638298" fontSize={10}/><YAxis domain={[0,100]} stroke="#638298" fontSize={10}/><Tooltip contentStyle={{background:"#081422",border:"1px solid #244565"}}/><Legend/><ReferenceLine y={70} stroke="#ffbd5a" strokeDasharray="4 4" label={{value:"Humidity alert 70%",fill:"#ffbd5a",fontSize:9}}/><ReferenceLine y={30} stroke="#ff6e83" strokeDasharray="4 4" label={{value:"Temperature alert 30°C",fill:"#ff6e83",fontSize:9}}/><Line type="monotone" dataKey="temperature" name="Temperature °C" stroke="#ff6e83" strokeWidth={3} connectNulls dot={chart.length<4}/><Line type="monotone" dataKey="humidity" name="Humidity % RH" stroke="#37e1ed" strokeWidth={3} connectNulls dot={chart.length<4}/></LineChart></ResponsiveContainer></div>:<div className="chart-empty"><Activity/><b>No telemetry received yet</b></div>}</section>
 <section className="panel"><div className="section-heading"><div><ShieldCheck/><div><h3>Safety and access activity</h3><p>Separate state history for water leak, door contact and smoke sensors</p></div></div></div>{chart.length?<div className="chart binary-chart"><ResponsiveContainer><LineChart data={chart}><CartesianGrid stroke="#143247" strokeDasharray="4 5"/><XAxis dataKey="time" minTickGap={35} stroke="#638298" fontSize={10}/><YAxis domain={[0,1]} ticks={[0,1]} tickFormatter={v=>v?"TRIGGERED":"NORMAL"} width={75} stroke="#638298" fontSize={9}/><Tooltip formatter={v=>v?"TRIGGERED":"NORMAL"} contentStyle={{background:"#081422",border:"1px solid #244565"}}/><Legend/><Line type="stepAfter" dataKey="water_leak" name="Water leak" stroke="#37e1ed" strokeWidth={3} connectNulls dot={false}/><Line type="stepAfter" dataKey="door_open" name="Door contact" stroke="#ffbd5a" strokeWidth={3} connectNulls dot={false}/><Line type="stepAfter" dataKey="smoke" name="Smoke / fire" stroke="#ff5d74" strokeWidth={3} connectNulls dot={false}/></LineChart></ResponsiveContainer></div>:<div className="chart-empty"><ShieldCheck/><b>No safety telemetry received yet</b></div>}</section>
 <Table title="Validated telemetry records" rows={telemetry} columns={["measurement_type","value_numeric","unit","quality_status","measurement_timestamp"]}/></>}

function diagnosticText(value){if(value===null||value===undefined)return "No details";if(typeof value!=="object")return String(value);return Object.entries(value).map(([key,item])=>`${key.replaceAll("_"," ")}: ${item}`).join(" · ")}
function OperationalReports({summary,alerts,incidents,preferences}){
 const [diagnostics,setDiagnostics]=useState(null),[ai,setAi]=useState([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([api("/system/diagnostics"),api("/ai/results?limit=100")]).then(([d,a])=>{setDiagnostics(d);setAi(a);setError("")}).catch(e=>setError(e.message))},[summary.telemetry_points]);
 const severity=["critical","warning","info"].map(name=>({name,count:alerts.filter(a=>a.severity===name).length})),components=diagnostics?.components||[];
 return <><section className="report-hero"><div><FileBarChart/><span><small>OPERATIONAL REPORT</small><h2>System and monitoring insight</h2><p>Live evidence from the database, alert engine, AI pipeline and supporting services.</p></span></div><b>{diagnostics?.status||"collecting"}</b></section>{error&&<div className="terminal-error"><AlertTriangle/>Unable to load diagnostics: {error}</div>}<section className="cards"><Card icon={<Activity/>} label="Stored readings" value={summary.telemetry_points||0}/><Card icon={<AlertTriangle/>} label="Active alerts" value={summary.open_alerts||0}/><Card icon={<ClipboardCheck/>} label="Open tickets" value={summary.open_incidents||0}/><Card icon={<BrainCircuit/>} label="AI analyses" value={ai.length}/></section><div className="report-grid">{preferences.reportSeverity&&<section className="panel"><h3>Alert severity distribution</h3><div className="report-chart"><ResponsiveContainer><BarChart data={severity}><CartesianGrid stroke="#143247"/><XAxis dataKey="name" stroke="#638298"/><YAxis allowDecimals={false} stroke="#638298"/><Tooltip contentStyle={{background:"#081422",border:"1px solid #244565"}}/><Bar dataKey="count" fill="#37e1ed" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section>}{preferences.reportHealth&&<section className="panel"><h3>Backend and service health</h3><div className="health-list">{components.length?components.map((c,i)=><article key={c.name||i}><i className={c.status==="healthy"?"ok":"bad"}/><span><b>{c.name||c.component}</b><small>{diagnosticText(c.detail||c.message||c.status)}</small></span><em>{c.status}</em></article>):<div className="empty-state">Collecting diagnostic evidence…</div>}</div></section>}</div>{preferences.reportFindings&&<section className="panel"><h3>Current operational findings</h3><div className="findings"><p><b>{incidents.filter(i=>i.status!=="closed").length}</b> tickets require operator action.</p><p><b>{alerts.length}</b> alert records are available for investigation.</p><p><b>{ai.length}</b> AI results are linked to processed sensor events.</p><p><b>{summary.telemetry_points||0}</b> validated telemetry values are stored in PostgreSQL/TimescaleDB.</p></div></section>}</>}

async function downloadSystemLog(){const token=localStorage.getItem("token"),response=await fetch(`${import.meta.env.VITE_API_URL||"http://localhost:8000/api/v1"}/admin/logs/export`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("Unable to export system log");const blob=await response.blob(),link=document.createElement("a"),disposition=response.headers.get("Content-Disposition")||"";link.href=URL.createObjectURL(blob);link.download=disposition.match(/filename="?([^";]+)"?/)?.[1]||`vtab-sentinel-system-log-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)}
function ApplicationSettings({preferences,updatePreference}){const [exportMessage,setExportMessage]=useState("");async function download(){try{setExportMessage("Preparing CSV...");await downloadSystemLog();setExportMessage("CSV downloaded successfully")}catch(error){setExportMessage(error.message)}}return <><section className="settings-hero"><SlidersHorizontal/><div><small>APPLICATION PREFERENCES</small><h2>Dashboard, reporting, voice and data export</h2><p>Changes apply immediately and remain saved in this browser.</p></div></section><div className="settings-grid"><section className="panel settings-card"><Volume2/><h3>Voice intelligence reminders</h3><p>Repeat active ticket announcements until an operator closes or resolves them.</p><label>Reminder interval<select value={preferences.voiceRepeatSeconds} onChange={e=>updatePreference("voiceRepeatSeconds",Number(e.target.value))}><option value={0}>Do not repeat</option><option value={10}>Every 10 seconds</option><option value={30}>Every 30 seconds</option><option value={60}>Every 60 seconds</option></select></label></section><section className="panel settings-card"><LayoutDashboard/><h3>Overview sections</h3><SettingToggle label="Tickets requiring action" value={preferences.showTickets} onChange={v=>updatePreference("showTickets",v)}/><SettingToggle label="Live temperature trend" value={preferences.showTrend} onChange={v=>updatePreference("showTrend",v)}/><SettingToggle label="Live alert feed" value={preferences.showAlertFeed} onChange={v=>updatePreference("showAlertFeed",v)}/></section><section className="panel settings-card"><FileBarChart/><h3>Report sections</h3><SettingToggle label="Alert severity chart" value={preferences.reportSeverity} onChange={v=>updatePreference("reportSeverity",v)}/><SettingToggle label="Backend service health" value={preferences.reportHealth} onChange={v=>updatePreference("reportHealth",v)}/><SettingToggle label="Operational findings" value={preferences.reportFindings} onChange={v=>updatePreference("reportFindings",v)}/></section><section className="panel settings-card"><FileBarChart/><h3>System log export</h3><p>Download one dated CSV containing core events, alerts, tickets, workflow actions and AI analyses.</p><button className="primary" onClick={download}><FileBarChart/> Download current CSV</button>{exportMessage&&<small className="export-message">{exportMessage}</small>}</section></div></>}
function SettingToggle({label,value,onChange}){return <label className="preference-toggle"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><i/></label>}

function IncidentCenter({incidents,onClose}){const [range,setRange]=useState("all"),[sort,setSort]=useState("desc");const now=Date.now(),todayStart=new Date().setHours(0,0,0,0),days={"3m":90,"6m":180,"1y":365};const rows=incidents.filter(item=>{if(range==="all")return true;const stamp=new Date(item.created_at||item.event_timestamp).getTime();return range==="today"?stamp>=todayStart:now-stamp<=days[range]*86400000}).slice().sort((a,b)=>(new Date(a.created_at)-new Date(b.created_at))*(sort==="asc"?1:-1));return <><section className="incident-toolbar"><div><ClipboardCheck/><span><b>Incident investigation</b><small>Filter and sort database-backed ticket history</small></span></div><label>Date range<select value={range} onChange={e=>setRange(e.target.value)}><option value="today">Today</option><option value="3m">Last 3 months</option><option value="6m">Last 6 months</option><option value="1y">Last year</option><option value="all">All history</option></select></label><label>Date order<select value={sort} onChange={e=>setSort(e.target.value)}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select></label><em>{rows.length} tickets</em></section><TicketQueue title="Incident and ticket workflow" rows={rows} onClose={onClose}/></>}

function Card({icon,label,value,warn}){return <div className={`card ${warn?"warn":""}`}><div className="icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
function relativeTime(value){if(!value)return "-";const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<5)return "just now";if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;return new Date(value).toLocaleString()}
function TicketQueue({title,rows,onClose,onViewAll}){const active=rows.filter(x=>["open","assigned","acknowledged"].includes(x.status)).length;return <section className="panel ticket-panel"><div className="section-heading"><div><ClipboardCheck/><div><h3>{title}</h3><p>Every ticket is recorded with its database-backed action history</p></div></div><div className="ticket-heading-actions"><span>{active} ACTIVE</span>{onViewAll&&<button className="refresh" onClick={onViewAll}>Open incident center</button>}</div></div><div className={`ticket-list ${rows.length===1?"single":""}`}>{rows.length?rows.map(ticket=><article className={`ticket ${ticket.status}`} key={ticket.id}><div><span className={`severity ${ticket.severity}`}>{ticket.severity}</span><small>#{ticket.id.slice(0,8)} · {relativeTime(ticket.event_timestamp||ticket.created_at)}</small></div><h4>{ticket.message||ticket.alert_type}</h4><p>{ticket.recommendation}</p><div className="ticket-metadata"><span>Raised</span><b>{new Date(ticket.created_at||ticket.event_timestamp).toLocaleString()}</b><span>Current status</span><b>{ticket.status}</b></div><details className="ticket-history"><summary>View database action history ({(ticket.history?.length||0)+1})</summary><div><article><i/><span><b>Ticket created</b><small>{new Date(ticket.created_at||ticket.event_timestamp).toLocaleString()} · VTAB alert engine</small></span></article>{ticket.history?.map(item=><article key={item.id}><i/><span><b>{item.action_type.replaceAll("_"," ")}</b><small>{new Date(item.timestamp).toLocaleString()} · {item.description}{item.note?` · ${item.note}`:""}</small></span></article>)}</div></details><footer><span>{ticket.room_name} · {ticket.device_name} · <b>{ticket.status}</b></span>{["open","assigned","acknowledged"].includes(ticket.status)&&<button onClick={()=>onClose(ticket.id)}><CheckCircle2/> Mark handled and close</button>}</footer></article>):<div className="empty-state ticket-empty"><CheckCircle2/><b>No tickets require action</b><span>The monitored environment is healthy. New incidents will appear here automatically.</span>{onViewAll&&<button className="refresh" onClick={onViewAll}>View incident history</button>}</div>}</div></section>}
function AlertFeed({title,rows,onOpen}){return <section className="panel"><div className="section-heading"><div><BellRing/><div><h3>{title}</h3><p>Dynamic events from the sensor-to-incident pipeline</p></div></div>{onOpen&&<button className="refresh" onClick={onOpen}>View all</button>}</div><div className="alert-feed">{rows.length?rows.map(a=><article className={`alert-item ${a.severity}`} key={a.id}><div className="alert-symbol"><AlertTriangle/></div><div className="alert-copy"><div><strong>{a.message||a.alert_type.replaceAll("_"," ")}</strong><span className={`severity ${a.severity}`}>{a.severity}</span></div><p>{a.recommendation||"Operator review is required."}</p><small>{a.room_name||"Server Room"} · {a.device_name||"ESP32"} · {relativeTime(a.event_timestamp||a.created_at)}</small></div></article>):<div className="empty-state">No alerts yet. Use Test Lab to generate a live event.</div>}</div></section>}
function Table({title,rows,columns}){return <section className="panel"><h2>{title}</h2><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c}>{r[c]===null||r[c]===undefined?"-":c.includes("timestamp")||c.endsWith("_at")?relativeTime(r[c]):String(r[c])}</td>)}</tr>):<tr><td colSpan={columns.length}>No data yet. Use Test Lab to generate sensor readings.</td></tr>}</tbody></table></div></section>}

class ErrorBoundary extends React.Component{constructor(props){super(props);this.state={error:null}}static getDerivedStateFromError(error){return{error}}render(){if(this.state.error)return <main className="page-crash"><AlertTriangle/><h1>This view could not be displayed</h1><p>{this.state.error.message}</p><button className="primary" onClick={()=>{this.setState({error:null});location.reload()}}><RefreshCw/> Reload dashboard</button></main>;return this.props.children}}
createRoot(document.getElementById("root")).render(<ErrorBoundary>{localStorage.getItem("token")?<VoiceProvider><App/></VoiceProvider>:<Login/>}</ErrorBoundary>);
